resources:
  - cronjob.yaml
  - role.yaml
namespace: gitlab

images:
  - name: cleanup-gitlab
    newName: ghcr.io/azman0101/clean-pods
    newTag: master@sha256:376e6f5e8bb699f2b2e6a20d184646edbee7e9ddacef85873843984bce70c876
